### ISSUE TITLE
npm version not the same as the repo

### ISSUE THREAD

**Issue by alumni** [jowavp/sap-cf-axios#13]
Thanks for creating the libraries, especially for sap-cf-destconn.

I can see sap-cf-axios@0.3.4 on npm, but I can't find anything about the changes between 0.2.36 and 0.3.4 in this repo. Could you also update the repo please?

**Comment by jowavp** [comment]
Sorry for that. It is fixed now.

I updated all dependend libraries and changed the code so it is using only axios interceptors.
This should be easier when you use typescript as it will just return the AxiosInstance now instead of a function.
