### ISSUE TITLE
Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by hosssa** [jowavp/sap-cf-axios#14]
https://github.com/jowavp/sap-cf-axios/blob/25bbe90f7755c8bba55b49a0fdffb4a6b94bf4de/dist/index.js#L119
Has caused an _"Unexpected token o in JSON at position 1"_ error.

Shouldn't it rather be a `JSON.stringify()` instead of `JSON.parse()`? Aren't `error` and `error.request` json objects yet? 

Furthermore it would be great to customize the logger for `logAxiosError`. I am using [cf-nodejs-logging-support](/SAP/cf-nodejs-logging-support) in my project, but `logAxiosError` simply dumps to the console.

**Comment by smug1414** [comment]
Hi 

We have the same issue with the logAxiosError dump in console. Should we write our own intercepter or is this something we can look forward to being fixed in a more elegant way?

Thanks for the package so far!

**Comment by jowavp** [comment]
Hi @hosssa 

Thanks for your feedback. 
replaced the JSON.parse with JSON.stringify and added the possibility to send your logger with the request in the logger property of the config object.

kr,
Joachim
