### ISSUE TITLE
Retrieving destination configuration fails due to expired token

### ISSUE THREAD

**Issue by hosssa** [jowavp/sap-cf-axios#15]
Please fix the issue jowavp/sap-cf-destconn#8 in [sap-cf-destconn](https://github.com/jowavp/sap-cf-destconn) and update this repo accordingly. 
Thanks, Frank

**Comment by mattreddy3** [comment]
Hi, judging the connected issue being closed and the dependencies being updated, this is also closed, correct?

**Comment by jowavp** [comment]
indeed, should be solved.

kr,
Jowa
