### ISSUE TITLE
OAuth2ClientCredentials destination

### ISSUE THREAD

**Issue by T1mey** [jowavp/sap-cf-axios#7]
Hi,

I use a destination of type "OAuth2ClientCredentials". The token creation request completes with HTTP 200 and delivers the access_token.
The call the the endpoint URL in my destination now fails because in the Authorization header is set to

`BearerToken` xxxxxxxx and not just `Bearer` xxxxxxxx

**Comment by T1mey** [comment]
@jowavp any hint where the auth header is created and why BearerToken is used?

**Comment by jowavp** [comment]
@T1mey Issue fixed in version 2.31

kr
Jowa

**Comment by T1mey** [comment]
@jowavp on npmjs the version is released... but the github repo is not showing any commit.
