### ISSUE TITLE
OAuth2ClientCredentials : bearer token is missing 

### ISSUE THREAD

**Issue by mconvertino** [jowavp/sap-cf-axios#9]
Hi,

I am using a destination of type "OAuth2ClientCredentials" to reach an OData API published in SAP Ariba. The access token is fetched correctly with the destination, however Ariba doesn't recognize it as it is set by the library as "bearer" (Authorization': 'bearer xxxx') instead of "Bearer" (Authorization': 'Bearer xxxx') .

This is the request headers sent
![image](https://user-images.githubusercontent.com/55501964/137912139-1cb56598-42ba-41be-9ed8-1540d47bea25.png)

and the following is the response from Ariba
![image](https://user-images.githubusercontent.com/55501964/137912174-247d7e8d-3126-4fa4-9826-189313b74ae5.png)

The token is correct as if I use it in a request with the header 'Authorization': 'Bearer xxxx' using a destination with authentication set to None the request is accepted. But this solution require me to do a separate request to fetch the token manually.

**Comment by jowavp** [comment]
This is because the destination is sending 'bearer' as token type.
I made a quick fix to solve this issue. please try 0.2.35
